"""password manager table

Revision ID: 859200bec47e
Revises: 
Create Date: 2018-11-19 00:08:53.709000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859200bec47e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=64), nullable=True),
    sa.Column('site_url', sa.String(length=128), nullable=True),
    sa.Column('login_account_name', sa.String(length=128), nullable=True),
    sa.Column('login_password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_account_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_manager')
    # ### end Alembic commands ###
